addr: ":8080"
log_level: "info"
default_storage: "memory"
document_store: "sqlite"
sqlite_path: "document-archive.db"
deleted_sweep_interval: "24h"
allow_cors: []
s3:
  endpoint: ""
  bucket: ""
  region: "us-east-1"
  access_key_id: ""
  secret_access_key: ""
  session_token: ""
  use_path_style: false
role:
  "admin-token":
    name: "admin"
    admin: true
  "contributor-token":
    name: "contributor"
    permissions:
      - "document:create"
      - "document:read"
  "viewer-token":
    name: "viewer"
    permissions:
      - "document:read"
